### ISSUE TITLE
Contribution on CA engine

### ISSUE THREAD

**Issue by dnqbob** [Inq8/CAmod#10]
Hi, here.
I want to ask where is the CA engine repo? I want to do some AI related pull request on it.

**Comment by Inq8** [comment]
https://github.com/Inq8/OpenRA/tree/prep-CA

However,

I normally clone the AI-related features and put them in the mod repo. See https://github.com/Inq8/CAmod/tree/master/OpenRA.Mods.CA/Traits/BotModules
