### ISSUE TITLE
Suggestion for armed soviet harvesters

### ISSUE THREAD

**Issue by ThunderTechnologies** [Inq8/CAmod#16]
I was thinking that since the allies get chronominers when an ore purifier is built, that it may make sense to give the soviets a similar thing.
Any thoughts on making it so the soviets get their armed harvesters when the industrial plant is built?

**Comment by Inq8** [comment]
At present we are refining a list of new upgrades to feature in the next update. I can't guarantee armed soviet harvesters will make it in the next release but I will add it to a list for future ideas & discussion.
