### ISSUE TITLE
Localization permission for CA

### ISSUE THREAD

**Issue by dnqbob** [Inq8/CAmod#20]
@Inq8 @darkademic

I want to ask for permission for Chinese Localization for CA, which the localization team leader @HansNihall think is a quite exquisite mod, although it has an appearance of first generation of CNC at first glance. Could you please give us the permission on localization for next stable release of CA?

### Description of localization version

Because OpenRA doesn't have a good localization module for now, especially many texts in gameplay related to engine itself, so the localization version **will be a different mod**. After it is done it will be put in [this page of Moddb](https://www.moddb.com/mods/openra-simplified-chinese-mod-series) and you can check it out.

**Comment by Inq8** [comment]
Yes, absolutely you have my permission to translate the mod & host it on Moddb.

I am honoured you enjoy it.

**Comment by dnqbob** [comment]
Thanks! If OpenRA finally apply a localization module in the future,  we will be able to directly work on our localization here instead of end up with another mod.
