### ISSUE TITLE
Lack of attribution towards a specific AS contributor.

### ISSUE THREAD

**Issue by GraionDilach** [Inq8/CAmod#21]
While it is very nice to see Combined Arms using code from Attacque Supérior, it does so without acknowledging a specific AS contributor whose feature were transferred. **Gerseras** never contributed to upstream OpenRA and with CA using his IvanBombs implementation from https://github.com/AttacqueSuperior/Engine/pull/26, is missing from the CA credits list.

**Comment by Inq8** [comment]
Thanks for bringing this to my attention.
 I will amend the credits to include Gerseras.
