### ISSUE TITLE
Game crashes with System.InvalidOperationException

### ISSUE THREAD

**Issue by metinc** [Inq8/CAmod#4]
I was playing skirmish 3 on 3 and the game crashed. For now I don't know how to replicate this bug but I will try.
Here is the exception log:

> OpenRA engine version d006601
> Combined Arms mod version 0.61
> on map 3bf3c4089a18341cd8bf29cfc7bb88c777bd3e2f (Bombardment Islands by Sprog).
> Date: 2020-01-31 23:37:57Z
> Operating System: Linux (Unix 5.4.12.200)
> Runtime Version: Mono 6.4.0.198 (tarball Tue Sep 24 01:20:30 UTC 2019) CLR 4.0.30319.42000
> Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
>   at OpenRA.Traits.Target.get_CenterPosition () [0x0003e] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Mods.Common.Activities.FlyAttackRun.OnFirstRun (OpenRA.Actor self) [0x00000] in /home/travis/build/Inq8/CAmod/engine/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs:225 
>   at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x00034] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00015] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Activities.Activity.TickChild (OpenRA.Actor self) [0x00008] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0004a] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00015] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Actor.Tick () [0x0000f] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.World.Tick () [0x00123] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001bc] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Game.LogicTick () [0x0003e] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Game.Loop () [0x000e3] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Game.Run () [0x0003c] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <e2d63584cafd4cda93b72a2fef918630>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x00044] in <e2d63584cafd4cda93b72a2fef918630>:0 
>

**Comment by metinc** [comment]
Actually this is a bug inside the engine.

**Comment by GraionDilach** [comment]
@pchote I have had reported this here for you btw: https://www.openra.net/#comment-4779963934
