### ISSUE TITLE
Game crashes when losing technology

### ISSUE THREAD

**Issue by muramasatheninja** [Inq8/CAmod#42]
I've found on the latest version the game will frequently crash when you lose something like temple prime or a gdi tech center. I went ahead and attached a crash log.
[exception-2022-01-06T073228Z.log](https://github.com/Inq8/CAmod/files/7825808/exception-2022-01-06T073228Z.log)
.

**Comment by Inq8** [comment]
Hey, thanks for the report.
We are already aware of this issue and we have a speculative fix already in place.
This should be fixed in the next dev version.
