### ISSUE TITLE
Flag of the UkrSSR is wrong.

### ISSUE THREAD

**Issue by Leo512bit** [Inq8/CAmod#43]
It should look like [this](https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_the_Ukrainian_Soviet_Socialist_Republic.svg).

**Comment by Inq8** [comment]
It was changed to be more distinct from the Soviet Russian flag

**Comment by Leo512bit** [comment]
Why?

**Comment by amoskopp** [comment]
The new flag makes it very clear which faction is Ukraine.

I like the change, given that the real flags are too similar.

Also, the entire game is not historically accurate anyway.
