### ISSUE TITLE
Pressing V (upgrade) with atomic heavy tanks selected upgrades them to lasher tanks even for soviet factions other than Psi Corps.

### ISSUE THREAD

**Issue by totbuae** [Inq8/CAmod#51]
Context:
1. Run 0.91 Combined Arms - Pre Release 2.
2. Play as a soviet faction other than Psi Corps (I first noticed the bug while playing as Russia and the bug also happened while playing as Iraq).
3. A service depot is available.
4. Atomic engines is researched.
5. There are some extant heavy tanks without the atomic engine upgrades.

How to reproduce:
1. Select the extant, unupgraded heavy tanks.
2. Press V (upgrade).
3. Wait for the upgrade to finish.
4. Select the newly upgraded atomic engine heavy tanks.
6. Press V (upgrade) once again.
7. The atomic engine heavy tanks upgrade to atomic engine lasher tanks even though the faction being used is not Psi Corps.

**Comment by Inq8** [comment]
Fixed
