### ISSUE TITLE
As ARC, upgrading battle tanks equipped with minidrones removes the minidrones.

### ISSUE THREAD

**Issue by totbuae** [Inq8/CAmod#52]
Context:
1. Run 0.91-PreRelease-2.
2. The battle drone upgrade is researched.
3. A repair bay is available.
4. There are some extant battle tanks equipped with minidrones which are not yet upgraded to battle drones.

How to reproduce:
1. Select the extant, unupgraded battle tanks equipped with minidrones.
2. Press "V" (upgrade).
3. The battle tanks are upgraded to battle drones but the already attached minidrones are removed.

**Comment by Inq8** [comment]
Fixed
