### ISSUE TITLE
openSUSE Build Service builds are failing at commit f59fe52, but manual build doesn't

### ISSUE THREAD

**Issue by fusion809** [Inq8/CAmod#6]
Hi,

This mod builds fine, when built manually but I get an odd build error in the OBS, that I'm hoping you'll help me fix. Here's the error, but a few lines before it for context:

```bash
[   20s] + make
[   20s] CSC OpenRA.Game.exe
[   22s] CSC OpenRA.Platforms.Default.dll
[   22s] CSC mods/common/OpenRA.Mods.Common.dll
[   24s] OpenRA.Mods.Common/Activities/Air/ScriptedTakeOff.cs(23,18): error CS0414: Warning as Error: The private field `OpenRA.Mods.Common.Activities.ScriptedTakeOff.move' is assigned but its value is never used
```

For my full log see: https://gist.github.com/e24f2eec7196e2be6b392c2899e773d3. My packaging files (which specify exactly how this is built) are here: https://build.opensuse.org/package/show/home:fusion809/openra-ca. This sounds like a programming error that just doesn't show up with regular Linux builds. Am I right there or is this merely my own packaging mess that I'm on my own to fix?

Thanks for your time and patience,
Brenton

**Comment by Inq8** [comment]
@fusion809 can you try 0.53.6 & see if you have the same issues? Thanks

**Comment by fusion809** [comment]
I've decided to ditch the OBS, it causes too many problems to be worth it, especially since I don't even know if anyone uses the packages I build. I use AppImages to run it now. Thanks for taking the time to attempt to help me though :).
