### ISSUE TITLE
Incorrect Bridge Issues on Desert Tileset

### ISSUE THREAD

**Issue by gatekeep** [Inq8/CAmod#6]
I have not tried other tilesets, but I was building a map for Combined Arms and found some terrain issues on desert maps. It seems with the default world.yaml rules shipped from Git and the current release packages, there are some defined entries for the bridge layer that are incorrect. 

This issue does not present it in the map editor only when in-game.

I've determined the cause to be the "LegacyBridgeLayer" entry in the world.yaml rules.
`	LegacyBridgeLayer:
		Bridges: bridge1, bridge2, br1, br2, br3, sbridge1, sbridge2, sbridge3, sbridge4, sbridge5, brg1, brg2, brg3, brv1, brv2, brv3, brh1, brh2, brh3`

If we remove brv1, brv2, brv3, brh1, brh2, brh3 the terrain issues are fixed and we no longer have incorrect random bridges.

Screenshot with the original "LegacyBridgeLayer" options (various debug display options are enabled to show terrain and actor information):
![Image 2](https://user-images.githubusercontent.com/1149277/79081251-ac68e080-7ce9-11ea-9858-7ea490994c9e.png)

Screenshot with the "LegacyBridgeLayer" options modified to remove "brv1, brv2, brv3, brh1, brh2, brh3" (various debug display options are enabled to show terrain and actor information):
![Image 4](https://user-images.githubusercontent.com/1149277/79081258-c0acdd80-7ce9-11ea-97d0-192f9dca3a68.png)

**Comment by Inq8** [comment]
Thanks, I screwed up the bridge ID's so those tiles thought they were bridges.

Should be fixed now.
