### ISSUE TITLE
Game crashes when playing as Germans missing Tank Destroyer Icon

### ISSUE THREAD

**Issue by muramasatheninja** [Inq8/CAmod#7]
So when ever playing as the Germans the game will crash once you build a War Factory. With the following tidbit in the log.
"Exception of type `System.InvalidOperationException`: Unit `td` does not have a sequence named `icon`"

I'm assuming td stands for Tank Destroyer, and the icon is missing.

**Comment by Inq8** [comment]
@muramasatheninja Let me know if you still experience this bug with release 0.53.7, Are you on Linux?

**Comment by muramasatheninja** [comment]
Yes I am using linux. I probably should have mentioned that. I just tried it with 0.53.7 and I can no play as Germans.

Thanks!
