### ISSUE TITLE
DependencyResolution.targets(234,5): error NETSDK1004: Assets file '/OpenRA.Mods.CA/C:/Users/F/Documents/GitHub/CAmod/OpenRA.Mods.CA/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. 

### ISSUE THREAD

**Issue by fusion809** [Inq8/CAmod#8]
Hi,

I'm currently getting this error when I run `make`:

```bash
  OpenRA.PostProcess -> /data/GitHub/others/CAmod/engine/OpenRA.PostProcess.exe
  OpenRA.Game -> /data/GitHub/others/CAmod/engine/OpenRA.Game.exe
  OpenRA.Mods.Common -> /data/GitHub/others/CAmod/engine/mods/common/OpenRA.Mods.Common.dll
/usr/lib/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/data/GitHub/others/CAmod/OpenRA.Mods.CA/C:/Users/F/Documents/GitHub/CAmod/OpenRA.Mods.CA/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/data/GitHub/others/CAmod/OpenRA.Mods.CA/OpenRA.Mods.CA.csproj]
  OpenRA.Mods.Cnc -> /data/GitHub/others/CAmod/engine/mods/common/OpenRA.Mods.Cnc.dll
```

with commit 94621d247c937f295374d78f651c5e125d3618f6. 

Thanks for your time,
Brenton

**Comment by Inq8** [comment]
I have removed some unnecessary files that may have been leading your system astray. Can you try again & see how you go?

Failing that I'll probably need to seek help for this.

**Comment by GraionDilach** [comment]
https://github.com/Inq8/CAmod/blob/master/OpenRA.Mods.CA/OpenRA.Mods.CA.csproj#L120 uses wrong backslashes. You might also want that `<Private>False</Private>` block along - I noticed omitting it duplicates the dll to the target folder.

Additionally, you no longer need to explicitly list all cs files by now.

**Comment by fusion809** [comment]
It is all fixed now.
